server: 
  port: 9001
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: [driverName]
    url: [url]
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
